/**
 * 16×16 farm sprites, painted as SVG rects so they stay sharp when scaled.
 *
 * The catalogue in economy.ts still names each crop with an emoji — that is
 * a label, not a drawing. Everything on the farm is drawn from here.
 */

const FILL: Record<string, string> = {
  k: 'var(--p-k)',
  g: 'var(--p-g)',
  G: 'var(--p-G)',
  y: 'var(--p-y)',
  r: 'var(--p-r)',
  o: 'var(--p-o)',
  s: 'var(--p-s)',
  w: 'var(--p-w)',
  b: 'var(--p-b)',
  W: 'var(--p-W)',
  p: 'var(--p-p)',
};

function cells(map: string): { x: number; y: number; fill: string }[] {
  const out: { x: number; y: number; fill: string }[] = [];
  map
    .trim()
    .split('\n')
    .forEach((line, y) => {
      [...line.trim()].forEach((ch, x) => {
        const fill = FILL[ch];
        if (fill) out.push({ x, y, fill });
      });
    });
  return out;
}

const SPRITES = {
  plus: cells(`
................
................
.......kk.......
.......kk.......
.......kk.......
.......kk.......
...kkkkkkkkkk...
...kkkkkkkkkk...
.......kk.......
.......kk.......
.......kk.......
.......kk.......
................
................
................
................
`),
  seed: cells(`
................
................
................
................
......ssss......
.....sswwss.....
....sswwwwss....
....sswwwwss....
.....sswwss.....
......ssss......
................
................
................
................
................
................
`),
  sprout: cells(`
................
................
........gg......
.......gGgg.....
......ggGgg.....
......Ggg.......
.......g........
.......ss.......
......ssss......
.....ssssss.....
................
................
................
................
................
................
`),
  filling: cells(`
................
.....gGggGg.....
....gggggggG....
...gGgggggggg...
...gggGgggGgg...
....gggggggg....
.....gGggGg.....
......gggg......
.......ss.......
......ssss......
.....ssssss.....
................
................
................
................
................
`),
  wheat: cells(`
................
..y..yyy..y.....
.yyyyyyyyyyy....
..yyyy.yyyy.....
...y.g.g.y......
....ggggg.......
.....ggg........
......g.........
......g.........
......ss........
.....ssss.......
....ssssss......
................
................
................
................
`),
  corn: cells(`
................
.....GGGGG......
....GyyyyyG.....
....GyGyGyG.....
....GyyyyyG.....
....GyGyGyG.....
....GyyyyyG.....
....GyGyGyG.....
.....GyyyG......
......GGG.......
.......G........
......sss.......
.....sssss......
................
................
................
`),
  tomato: cells(`
................
.......GGG......
......GGGGG.....
.....rrGGrrr....
....rrrrrrrrr...
...rrrrWrrrrr...
...rrrrkrrrrr...
...rrrrrrrrrr...
....rrrrrrrr....
.....rrrrr......
......sss.......
................
................
................
................
................
`),
  pumpkin: cells(`
................
.......GGG......
......ooGoo.....
....ooooooooo...
...ooooooooooo..
...oookokokooo..
...ooooooooooo..
...ooooooooooo..
....ooooooooo...
.....ooooooo....
......sssss.....
................
................
................
................
................
`),
  goldgrain: cells(`
................
.W.y.yyyy.y.W...
..yyyyyyyyyy....
.yyyyyyyyyyyy...
..y.y.yy.y.y....
....gggggg......
.....gggg.......
......gg........
......g.........
......ss........
.....ssss.......
....ssssss......
................
................
................
................
`),
  scarecrow: cells(`
................
......oooo......
.....oWWWWo.....
.....oWkWWo.....
......wwww......
....wwwwwwww....
...w.wwwwww.w...
......wwww......
......w..w......
......w..w......
.....ss..ss.....
................
................
................
................
................
`),
  fence: cells(`
................
.w...w...w...w..
.w...w...w...w..
.wwwwwwwwwwwww..
.w...w...w...w..
.w...w...w...w..
.wwwwwwwwwwwww..
.w...w...w...w..
.w...w...w...w..
................
................
................
................
................
................
................
`),
  pond: cells(`
................
................
....bbbbbbbbb...
...bbWbbbbbbbb..
...bbbbbpkbbb...
...bbbbbbbbbb...
...bbbbbbbbbb...
....bbbbbbbb....
.....ssssss.....
....ssssssss....
................
................
................
................
................
................
`),
  windmill: cells(`
W..........W....
.W........W.....
..W......W......
...W....W.......
....W..W........
.....kk.........
....WkkW........
...W..kk.W......
..W....kk.W.....
.W......kk.W....
W........kk.W...
.........kk.....
.........kk.....
........ssss....
.......ssssss...
................
`),
  coin: cells(`
................
.....yyyyyy.....
...yykkkkkkyy...
..yyk.yyyy.kyy..
..yykyyyyyykyy..
..yyk.ykk.ykyy..
..yykyyyyyykyy..
..yyk.yyyy.kyy..
..yyk.yyyy.kyy..
...yykkkkkkyy...
.....yyyyyy.....
................
................
................
................
................
`),
} as const;

export type SpriteId = keyof typeof SPRITES;

const CROPS: Record<string, SpriteId> = {
  wheat: 'wheat',
  corn: 'corn',
  tomato: 'tomato',
  pumpkin: 'pumpkin',
  goldgrain: 'goldgrain',
};

/** Which sprite a planting shows at this much growth. */
export function cropSprite(seedId: string, progress: number): SpriteId {
  if (progress >= 1) return CROPS[seedId] ?? 'wheat';
  if (progress >= 0.6) return 'filling';
  if (progress >= 0.25) return 'sprout';
  return 'seed';
}

export function asSprite(id: string): SpriteId {
  return id in SPRITES ? (id as SpriteId) : 'plus';
}

export function Pixel({
  sprite,
  size = 16,
  className,
}: {
  sprite: SpriteId;
  size?: number;
  className?: string;
}) {
  return (
    <svg
      className={className ? `px-icon ${className}` : 'px-icon'}
      width={size}
      height={size}
      viewBox="0 0 16 16"
      shapeRendering="crispEdges"
      aria-hidden
    >
      {SPRITES[sprite].map((cell, i) => (
        <rect key={i} x={cell.x} y={cell.y} width={1} height={1} fill={cell.fill} />
      ))}
    </svg>
  );
}
